<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'file extension invalid' => 'Định dạng file tải lên không hợp lệ. Hiện tại chỉ hỗ trợ các file JPG, JPEG, PNG',
    'account not exist' => 'account không tồn tại',
    'image is not blank' => 'Image khong duoc rong',
    'ncoin is not blank' => 'ncoin không được rỗng',
    'provider and client_id ís not blank' => 'provider và client_id không được rỗng',
    'username not exist' => 'username không tồn tại',
    'username or password is not blank' => 'Tên đăng nhập hoặc mật khẩu không được rỗng.',
    'username or password is not correct' => 'Tên đăng nhập hoặc mật khẩu không đúng.',
    'vcoin is not blank' => 'vcoin không được rỗng',
];
